# ruby encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# TODO: Seeds - revise this file once we receive the lists with info to build dropdowns and other elements

# Linked with User
Country.create([
                   { country_name: 'Colombia' },
                   { country_name: 'Afganistán' },
                   { country_name: 'Albania' },
                   { country_name: 'Alemania' },
                   { country_name: 'Andorra' },
                   { country_name: 'Angola' },
                   { country_name: 'Antigua y Barbuda' },
                   { country_name: 'Arabia Saudita' },
                   { country_name: 'Argelia' },
                   { country_name: 'Argentina' },
                   { country_name: 'Armenia' },
                   { country_name: 'Australia' },
                   { country_name: 'Austria' },
                   { country_name: 'Azerbaiyán' },
                   { country_name: 'Bahamas' },
                   { country_name: 'Bangladés' },
                   { country_name: 'Barbados' },
                   { country_name: 'Baréin' },
                   { country_name: 'Bélgica' },
                   { country_name: 'Belice' },
                   { country_name: 'Benín' },
                   { country_name: 'Bielorrusia' },
                   { country_name: 'Birmania' },
                   { country_name: 'Bolivia' },
                   { country_name: 'Bosnia y Herzegovina' },
                   { country_name: 'Botsuana' },
                   { country_name: 'Brasil' },
                   { country_name: 'Brunéi' },
                   { country_name: 'Bulgaria' },
                   { country_name: 'Burkina Faso' },
                   { country_name: 'Burundi' },
                   { country_name: 'Bután' },
                   { country_name: 'Cabo Verde' },
                   { country_name: 'Camboya' },
                   { country_name: 'Camerún' },
                   { country_name: 'Canadá' },
                   { country_name: 'Catar' },
                   { country_name: 'Chad' },
                   { country_name: 'Chile' },
                   { country_name: 'China' },
                   { country_name: 'Chipre' },
                   { country_name: 'Ciudad del Vaticano' },
                   { country_name: 'Comoras' },
                   { country_name: 'Corea del Norte' },
                   { country_name: 'Corea del Sur' },
                   { country_name: 'Costa de Marfil' },
                   { country_name: 'Costa Rica' },
                   { country_name: 'Croacia' },
                   { country_name: 'Cuba' },
                   { country_name: 'Dinamarca' },
                   { country_name: 'Dominica' },
                   { country_name: 'Ecuador' },
                   { country_name: 'Egipto' },
                   { country_name: 'El Salvador' },
                   { country_name: 'Emiratos Árabes Unidos' },
                   { country_name: 'Eritrea' },
                   { country_name: 'Eslovaquia' },
                   { country_name: 'Eslovenia' },
                   { country_name: 'España' },
                   { country_name: 'Estados Unidos' },
                   { country_name: 'Estonia' },
                   { country_name: 'Etiopía' },
                   { country_name: 'Filipinas' },
                   { country_name: 'Finlandia' },
                   { country_name: 'Fiyi' },
                   { country_name: 'Francia' },
                   { country_name: 'Gabón' },
                   { country_name: 'Gambia' },
                   { country_name: 'Georgia' },
                   { country_name: 'Ghana' },
                   { country_name: 'Granada' },
                   { country_name: 'Grecia' },
                   { country_name: 'Guatemala' },
                   { country_name: 'Guinea' },
                   { country_name: 'Guinea ecuatorial' },
                   { country_name: 'Guinea-Bisáu' },
                   { country_name: 'Guyana' },
                   { country_name: 'Haití' },
                   { country_name: 'Honduras' },
                   { country_name: 'Hungría' },
                   { country_name: 'India' },
                   { country_name: 'Indonesia' },
                   { country_name: 'Irak' },
                   { country_name: 'Irán' },
                   { country_name: 'Irlanda' },
                   { country_name: 'Islandia' },
                   { country_name: 'Islas Marshall' },
                   { country_name: 'Islas Salomón' },
                   { country_name: 'Israel' },
                   { country_name: 'Italia' },
                   { country_name: 'Jamaica' },
                   { country_name: 'Japón' },
                   { country_name: 'Jordania' },
                   { country_name: 'Kazajistán' },
                   { country_name: 'Kenia' },
                   { country_name: 'Kirguistán' },
                   { country_name: 'Kiribati' },
                   { country_name: 'Kuwait' },
                   { country_name: 'Laos' },
                   { country_name: 'Lesoto' },
                   { country_name: 'Letonia' },
                   { country_name: 'Líbano' },
                   { country_name: 'Liberia' },
                   { country_name: 'Libia' },
                   { country_name: 'Liechtenstein' },
                   { country_name: 'Lituania' },
                   { country_name: 'Luxemburgo' },
                   { country_name: 'Madagascar' },
                   { country_name: 'Malasia' },
                   { country_name: 'Malaui' },
                   { country_name: 'Maldivas' },
                   { country_name: 'Malí' },
                   { country_name: 'Malta' },
                   { country_name: 'Marruecos' },
                   { country_name: 'Mauricio' },
                   { country_name: 'Mauritania' },
                   { country_name: 'México' },
                   { country_name: 'Micronesia' },
                   { country_name: 'Moldavia' },
                   { country_name: 'Mónaco' },
                   { country_name: 'Mongolia' },
                   { country_name: 'Montenegro' },
                   { country_name: 'Mozambique' },
                   { country_name: 'Namibia' },
                   { country_name: 'Nauru' },
                   { country_name: 'Nepal' },
                   { country_name: 'Nicaragua' },
                   { country_name: 'Níger' },
                   { country_name: 'Nigeria' },
                   { country_name: 'Noruega' },
                   { country_name: 'Nueva Zelanda' },
                   { country_name: 'Omán' },
                   { country_name: 'Países Bajos' },
                   { country_name: 'Pakistán' },
                   { country_name: 'Palaos' },
                   { country_name: 'Panamá' },
                   { country_name: 'Papúa Nueva Guinea' },
                   { country_name: 'Paraguay' },
                   { country_name: 'Perú' },
                   { country_name: 'Polonia' },
                   { country_name: 'Portugal' },
                   { country_name: 'Reino Unido' },
                   { country_name: 'República Centroafricana' },
                   { country_name: 'República Checa' },
                   { country_name: 'República de Macedonia' },
                   { country_name: 'República del Congo' },
                   { country_name: 'República Democrática del Congo' },
                   { country_name: 'República Dominicana' },
                   { country_name: 'República Sudafricana' },
                   { country_name: 'Ruanda' },
                   { country_name: 'Rumanía' },
                   { country_name: 'Rusia' },
                   { country_name: 'Samoa' },
                   { country_name: 'San Cristóbal y Nieves' },
                   { country_name: 'San Marino' },
                   { country_name: 'San Vicente y las Granadinas' },
                   { country_name: 'Santa Lucía' },
                   { country_name: 'Santo Tomé y Príncipe' },
                   { country_name: 'Senegal' },
                   { country_name: 'Serbia' },
                   { country_name: 'Seychelles' },
                   { country_name: 'Sierra Leona' },
                   { country_name: 'Singapur' },
                   { country_name: 'Siria' },
                   { country_name: 'Somalia' },
                   { country_name: 'Sri Lanka' },
                   { country_name: 'Suazilandia' },
                   { country_name: 'Sudán' },
                   { country_name: 'Sudán del Sur' },
                   { country_name: 'Suecia' },
                   { country_name: 'Suiza' },
                   { country_name: 'Surinam' },
                   { country_name: 'Tailandia' },
                   { country_name: 'Tanzania' },
                   { country_name: 'Tayikistán' },
                   { country_name: 'Timor Oriental' },
                   { country_name: 'Togo' },
                   { country_name: 'Tonga' },
                   { country_name: 'Trinidad y Tobago' },
                   { country_name: 'Túnez' },
                   { country_name: 'Turkmenistán' },
                   { country_name: 'Turquía' },
                   { country_name: 'Tuvalu' },
                   { country_name: 'Ucrania' },
                   { country_name: 'Uganda' },
                   { country_name: 'Uruguay' },
                   { country_name: 'Uzbekistán' },
                   { country_name: 'Vanuatu' },
                   { country_name: 'Venezuela' },
                   { country_name: 'Vietnam' },
                   { country_name: 'Yemen' },
                   { country_name: 'Yibuti' },
                   { country_name: 'Zambia' },
                   { country_name: 'Zimbabue' }
               ])

City.create([
                { city_name: 'Aguachica' },
                { city_name: 'Apartadó' },
                { city_name: 'Arauca' },
                { city_name: 'Armenia' },
                { city_name: 'Barrancabermeja' },
                { city_name: 'Barranquilla' },
                { city_name: 'Bello' },
                { city_name: 'Bogotá' },
                { city_name: 'Bucaramanga' },
                { city_name: 'Buenaventura' },
                { city_name: 'Buga' },
                { city_name: 'Cajicá' },
                { city_name: 'Caldas' },
                { city_name: 'Cali' },
                { city_name: 'Cartago' },
                { city_name: 'Cartagena' },
                { city_name: 'Caucasia' },
                { city_name: 'Cereté' },
                { city_name: 'Chía' },
                { city_name: 'Ciénaga' },
                { city_name: 'Cúcuta' },
                { city_name: 'Dosquebradas' },
                { city_name: 'Duitama' },
                { city_name: 'Envigado' },
                { city_name: 'Facatativa' },
                { city_name: 'Florencia' },
                { city_name: 'Floridablanca' },
                { city_name: 'Fusagasugá' },
                { city_name: 'Girardot' },
                { city_name: 'Girón' },
                { city_name: 'Guaduas' },
                { city_name: 'Ibagué' },
                { city_name: 'Ipiales' },
                { city_name: 'Itaguí' },
                { city_name: 'Jamundí' },
                { city_name: 'Leticia' },
                { city_name: 'Lorica' },
                { city_name: 'Los Patios' },
                { city_name: 'Magangué' },
                { city_name: 'Maicao' },
                { city_name: 'Malambo' },
                { city_name: 'Manizales' },
                { city_name: 'Medellín' },
                { city_name: 'Melgar' },
                { city_name: 'Mocoa' },
                { city_name: 'Montería' },
                { city_name: 'Neiva' },
                { city_name: 'Ocaña' },
                { city_name: 'Paipa' },
                { city_name: 'Palmira' },
                { city_name: 'Pamplona' },
                { city_name: 'Pasto' },
                { city_name: 'Pereira' },
                { city_name: 'Piedecuesta' },
                { city_name: 'Pitalito' },
                { city_name: 'Popayán' },
                { city_name: 'Puerto Asis' },
                { city_name: 'Quibdó' },
                { city_name: 'Riohacha' },
                { city_name: 'Rionegro' },
                { city_name: 'Sabanalarga' },
                { city_name: 'Sahagún' },
                { city_name: 'San Andrés' },
                { city_name: 'Santa Marta' },
                { city_name: 'Sincelejo' },
                { city_name: 'Soacha' },
                { city_name: 'Sogamoso' },
                { city_name: 'Soledad' },
                { city_name: 'Tabio' },
                { city_name: 'Tibú' },
                { city_name: 'Tuluá' },
                { city_name: 'Tumaco' },
                { city_name: 'Tunja' },
                { city_name: 'Turbo' },
                { city_name: 'Valledupar' },
                { city_name: 'Villa de Leyva' },
                { city_name: 'Villa del Rosario' },
                { city_name: 'Villavicencio' },
                { city_name: 'Yopal' },
                { city_name: 'Yumbo' },
                { city_name: 'Zipaquirá' }
            ])

# Linked with Student
University.create([
                      { university_name: 'Academia Superior de Artes - CORPOASA' },
                      { university_name: 'Cambridge' },
                      { university_name: 'Colegio de Estudios Superiores de Administración - CESA' },
                      { university_name: 'Corporación Universitaria Americana (Barranquilla)' },
                      { university_name: 'Corporación Universitaria Americana (Medellín)' },
                      { university_name: 'Corporación Universitaria Americana (Montería)' },
                      { university_name: 'Corporación Universitaria Americana (Virtual)' },
                      { university_name: 'Corporación Universitaria de Ciencia y Desarrollo - UNICIENCIA' },
                      { university_name: 'Corporación Universitaria Lasallista' },
                      { university_name: 'Corporación Universitaria Minuto de Dios - UNIMINUTO' },
                      { university_name: 'Corporación Universitaria Republicana' },
                      { university_name: 'Corporación Universitaria UNITEC' },
                      { university_name: 'Dirección Nacional de Escuelas' },
                      { university_name: 'EAFIT' },
                      { university_name: 'EAN' },
                      { university_name: 'ECCI (Bogotá)' },
                      { university_name: 'ECCI (Medellín)' },
                      { university_name: 'Escuela Colombiana de Ingeniería Julio Garavito' },
                      { university_name: 'Escuela de Artes y Letras' },
                      { university_name: 'Escuela de Diseño & Mercadeo de Moda Arturo Tejada Cano (Bogotá)' },
                      { university_name: 'Escuela de Diseño & Mercadeo de Moda Arturo Tejada Cano (Medellín)' },
                      { university_name: 'Escuela de Ingeniería de Antioquia - EIA' },
                      { university_name: 'Escuela de Posgrados Fuerza Aérea Colombiana' },
                      { university_name: 'Escuela Superior de Administración Pública - ESAP' },
                      { university_name: 'Escuela Superior de Guerra' },
                      { university_name: 'Fundación Universidad de América' },
                      { university_name: 'Fundación Universitaria Agraria de Colombia - UNIAGRARIA' },
                      { university_name: 'Fundación Universitaria del Área Andina' },
                      { university_name: 'Fundación Universitaria Konrad Lorenz' },
                      { university_name: 'Fundación Universitaria Los Libertadores (Bogotá)' },
                      { university_name: 'Fundación Universitaria Los Libertadores (Cartagena)' },
                      { university_name: 'Fundación Universitaria Luis Amigó' },
                      { university_name: 'Fundación Universitaria Monserrate' },
                      { university_name: 'ICESI' },
                      { university_name: 'Institución Universitaria CESMAG' },
                      { university_name: 'Institución Universitaria Colegio Mayor de Antioquia' },
                      { university_name: 'Institución Universitaria Politécnico Grancolombiano' },
                      { university_name: 'Instituto Colombiano de Aprendizaje - INCAP' },
                      { university_name: 'Instituto Tecnológico de Comitán' },
                      { university_name: 'Instituto Tecnológico Metropolitano - ITM' },
                      { university_name: 'Justus Liebig Universitat' },
                      { university_name: 'Politécnico Colombiano Jaime Isaza Cadavid' },
                      { university_name: 'Pontificia Universidad Javeriana (Bogotá)' },
                      { university_name: 'Pontificia Universidad Javeriana (Cali)' },
                      { university_name: 'Servicio Nacional de Aprendizaje - SENA' },
                      { university_name: 'Tecnológico de Antioquia' },
                      { university_name: 'Universidad Antonio Nariño' },
                      { university_name: 'Universidad Autónoma de Bucaramanga' },
                      { university_name: 'Universidad Autónoma de Colombia (Bogotá)' },
                      { university_name: 'Universidad Autónoma de Manizales' },
                      { university_name: 'Universidad Autónoma de Occidente (Cali)' },
                      { university_name: 'Universidad Autónoma del Caribe (Barranquilla)' },
                      { university_name: 'Universidad Autónoma Latinoamericana (Medellín)' },
                      { university_name: 'Universidad Católica de Colombia (Bogotá)' },
                      { university_name: 'Universidad Católica de Manizales' },
                      { university_name: 'Universidad Católica de Pereira' },
                      { university_name: 'Universidad Central' },
                      { university_name: 'Universidad CES' },
                      { university_name: 'Universidad Cooperativa de Colombia (Bogotá)' },
                      { university_name: 'Universidad Cooperativa de Colombia (Bucaramanga)' },
                      { university_name: 'Universidad Cooperativa de Colombia (Medellín)' },
                      { university_name: 'Universidad de Antioquia' },
                      { university_name: 'Universidad de Caldas' },
                      { university_name: 'Universidad de Cartagena' },
                      { university_name: 'Universidad de Ciencias Aplicadas y Ambientales - UDCA' },
                      { university_name: 'Universidad de Córdoba' },
                      { university_name: 'Universidad de Ibagué' },
                      { university_name: 'Universidad de la Amazonía' },
                      { university_name: 'Universidad de la Costa' },
                      { university_name: 'Universidad de la Sabana' },
                      { university_name: 'Universidad de la Salle' },
                      { university_name: 'Universidad de los Andes' },
                      { university_name: 'Universidad de los Llanos' },
                      { university_name: 'Universidad de Manizales' },
                      { university_name: 'Universidad de Medellín' },
                      { university_name: 'Universidad de Nariño' },
                      { university_name: 'Universidad de Pamplona' },
                      { university_name: 'Universidad de San Buenaventura (Bogotá)' },
                      { university_name: 'Universidad de San Buenaventura (Cali)' },
                      { university_name: 'Universidad de San Buenaventura (Medellín)' },
                      { university_name: 'Universidad de Santander' },
                      { university_name: 'Universidad de Sucre' },
                      { university_name: 'Universidad del Atlántico' },
                      { university_name: 'Universidad del Cauca' },
                      { university_name: 'Universidad del Magdalena' },
                      { university_name: 'Universidad del Norte' },
                      { university_name: 'Universidad del Quindío' },
                      { university_name: 'Universidad del Rosario' },
                      { university_name: 'Universidad del Tolima' },
                      { university_name: 'Universidad del Valle' },
                      { university_name: 'Universidad Distrital Francisco José de Caldas' },
                      { university_name: 'Universidad el Bosque' },
                      { university_name: 'Universidad Externado de Colombia' },
                      { university_name: 'Universidad Francisco de Paula Santander' },
                      { university_name: 'Universidad Incca de Colombia - UNINCCA' },
                      { university_name: 'Universidad Industrial de Santander' },
                      { university_name: 'Universidad Jorge Tadeo Lozano' },
                      { university_name: 'Universidad La Gran Colombia (Armenia)' },
                      { university_name: 'Universidad La Gran Colombia (Bogotá)' },
                      { university_name: 'Universidad Libre de Colombia (Barranquilla)' },
                      { university_name: 'Universidad Libre de Colombia (Bogotá)' },
                      { university_name: 'Universidad Libre de Colombia (Cali)' },
                      { university_name: 'Universidad Libre de Colombia (Pereira)' },
                      { university_name: 'Universidad Manuela Beltrán' },
                      { university_name: 'Universidad Mariana' },
                      { university_name: 'Universidad Militar Nueva Granada' },
                      { university_name: 'Universidad Nacional Abierta y a Distancia - UNAD' },
                      { university_name: 'Universidad Nacional de Colombia (Bogotá)' },
                      { university_name: 'Universidad Nacional de Colombia (Leticia)' },
                      { university_name: 'Universidad Nacional de Colombia (Medellín)' },
                      { university_name: 'Universidad Nacional de Colombia (Palmira)' },
                      { university_name: 'Universidad Pedagógica Nacional' },
                      { university_name: 'Universidad Pedagógica y Tecnológica de Colombia' },
                      { university_name: 'Universidad Piloto de Colombia' },
                      { university_name: 'Universidad Pontificia Bolivariana (Bucaramanga)' },
                      { university_name: 'Universidad Pontificia Bolivariana (Medellín)' },
                      { university_name: 'Universidad Popular del Cesar' },
                      { university_name: 'Universidad Santiago de Cali' },
                      { university_name: 'Universidad Santo Tomás (Bogotá)' },
                      { university_name: 'Universidad Santo Tomás (Bucaramanga)' },
                      { university_name: 'Universidad Santo Tomás (Tunja)' },
                      { university_name: 'Universidad Sergio Arboleda' },
                      { university_name: 'Universidad Simón Bolívar' },
                      { university_name: 'Universidad Surcolombiana' },
                      { university_name: 'Universidad Tecnológica de Bolívar' },
                      { university_name: 'Universidad Tecnológica de Pereira' },
                      { university_name: 'Universidad Tecnológica del Chocó' },
                      { university_name: 'Universidade de Sao Paulo' }
                  ])

Major.create([
                 { major_name: 'Administración ambiental' },
                 { major_name: 'Administración de empresas' },
                 { major_name: 'Administración de mercadeo y logística internacionales' },
                 { major_name: 'Administración de negocios' },
                 { major_name: 'Administración de negocios internacionales' },
                 { major_name: 'Administración de sistemas informáticos' },
                 { major_name: 'Administración turística y hotelera' },
                 { major_name: 'Administración y servicio' },
                 { major_name: 'Agua y saneamiento ambiental' },
                 { major_name: 'Antropología' },
                 { major_name: 'Arqueología' },
                 { major_name: 'Arquitectura' },
                 { major_name: 'Arte' },
                 { major_name: 'Artes escénicas' },
                 { major_name: 'Artes plásticas' },
                 { major_name: 'Biología' },
                 { major_name: 'Bioquímica' },
                 { major_name: 'Ciencia política' },
                 { major_name: 'Ciencia de la información - Bibliotecología' },
                 { major_name: 'Cine y televisión' },
                 { major_name: 'Comercio internacional' },
                 { major_name: 'Comercio internacional y finanzas' },
                 { major_name: 'Comunicación' },
                 { major_name: 'Comunicación audiovisual y multimedia' },
                 { major_name: 'Comunicación gráfica publicitaria' },
                 { major_name: 'Comunicación social' },
                 { major_name: 'Comunicación social y periodismo' },
                 { major_name: 'Contaduría' },
                 { major_name: 'Contaduría internacional' },
                 { major_name: 'Contaduría pública' },
                 { major_name: 'Derecho' },
                 { major_name: 'Derechos humanos y DIH' },
                 { major_name: 'Diseño' },
                 { major_name: 'Diseño de procesos y productos' },
                 { major_name: 'Diseño gráfico' },
                 { major_name: 'Diseño industrial' },
                 { major_name: 'Diseño interactivo' },
                 { major_name: 'Diseño y gestión de la moda' },
                 { major_name: 'Ecología' },
                 { major_name: 'Economía' },
                 { major_name: 'Educación' },
                 { major_name: 'Educación básica' },
                 { major_name: 'Educación continuada' },
                 { major_name: 'Emprendimiento' },
                 { major_name: 'Enfermería' },
                 { major_name: 'Español' },
                 { major_name: 'Estadística' },
                 { major_name: 'Estudios culturales' },
                 { major_name: 'Estudios dirigidos' },
                 { major_name: 'Estudios interdisciplinarios para el desarrollo' },
                 { major_name: 'Estudios internacionales' },
                 { major_name: 'Estudios literarios' },
                 { major_name: 'Farmacia' },
                 { major_name: 'Filología clásica' },
                 { major_name: 'Filosofía' },
                 { major_name: 'Finanzas' },
                 { major_name: 'Finanzas y comercio internacional' },
                 { major_name: 'Finanzas y negocios internacionales' },
                 { major_name: 'Física' },
                 { major_name: 'Fisioterapia' },
                 { major_name: 'Fotografía' },
                 { major_name: 'Geociencias' },
                 { major_name: 'Geografía' },
                 { major_name: 'Geología' },
                 { major_name: 'Gestión' },
                 { major_name: 'Gestión y desarrollo urbanos' },
                 { major_name: 'Gobierno' },
                 { major_name: 'Gobierno y asuntos públicos' },
                 { major_name: 'Gobierno y relaciones internacionales' },
                 { major_name: 'Historia' },
                 { major_name: 'Historia del arte' },
                 { major_name: 'Ingeniería' },
                 { major_name: 'Ingeniería aeronaútica' },
                 { major_name: 'Ingeniería agrícola' },
                 { major_name: 'Ingeniería agroecológica' },
                 { major_name: 'Ingeniería agroforestal' },
                 { major_name: 'Ingeniería agroindustrial' },
                 { major_name: 'Ingeniería agronómica' },
                 { major_name: 'Ingeniería ambiental' },
                 { major_name: 'Ingeniería biomédica' },
                 { major_name: 'Ingeniería catastral y geodesia' },
                 { major_name: 'Ingeniería civil' },
                 { major_name: 'Ingeniería de alimentos' },
                 { major_name: 'Ingeniería de diseño de producto' },
                 { major_name: 'Ingeniería de las artes digitales' },
                 { major_name: 'Ingeniería de petróleos' },
                 { major_name: 'Ingeniería de sistemas y computación' },
                 { major_name: 'Ingeniería de sonido' },
                 { major_name: 'Ingeniería eléctrica' },
                 { major_name: 'Ingeniería electrónica' },
                 { major_name: 'Ingeniería financiera' },
                 { major_name: 'Ingeniería forestal' },
                 { major_name: 'Ingeniería geológica' },
                 { major_name: 'Ingeniería industrial' },
                 { major_name: 'Ingeniería informática' },
                 { major_name: 'Ingeniería matemática' },
                 { major_name: 'Ingeniería mecánica' },
                 { major_name: 'Ingeniería mecatrónica' },
                 { major_name: 'Ingeniería química' },
                 { major_name: 'Ingeniería sanitaria' },
                 { major_name: 'Ingeniería topográfica' },
                 { major_name: 'Inglés' },
                 { major_name: 'Jurisprudencia' },
                 { major_name: 'Lenguajes' },
                 { major_name: 'Lenguajes y estudios socioculturales' },
                 { major_name: 'Lenguas' },
                 { major_name: 'Lenguas modernas' },
                 { major_name: 'Lenguas y cultura' },
                 { major_name: 'Lingüística' },
                 { major_name: 'Literatura' },
                 { major_name: 'Marketing' },
                 { major_name: 'Matemáticas' },
                 { major_name: 'Medicina' },
                 { major_name: 'Medicina veterinaria' },
                 { major_name: 'Medios electrónicos y artes del tiempo' },
                 { major_name: 'Mercadeo internacional y publicidad' },
                 { major_name: 'Mercadeo y publicidad' },
                 { major_name: 'Microbiología' },
                 { major_name: 'Microbiología industrial' },
                 { major_name: 'Música' },
                 { major_name: 'Negocios internacionales' },
                 { major_name: 'Oceanografía' },
                 { major_name: 'Odontología' },
                 { major_name: 'Operaciones comerciales' },
                 { major_name: 'Pedagogía' },
                 { major_name: 'Pedagogía infantil' },
                 { major_name: 'Periodismo' },
                 { major_name: 'Periodismo y opinión publica' },
                 { major_name: 'Producción de imagen fotográfica' },
                 { major_name: 'Producción radial' },
                 { major_name: 'Psicología' },
                 { major_name: 'Publicidad' },
                 { major_name: 'Química' },
                 { major_name: 'Química farmacéutica' },
                 { major_name: 'Relaciones internacionales' },
                 { major_name: 'Robótica y automatización industrial' },
                 { major_name: 'Salud pública' },
                 { major_name: 'Seguridad y defensa nacionales' },
                 { major_name: 'Sistematización de datos' },
                 { major_name: 'Sociología' },
                 { major_name: 'Tecnología en electrónica' },
                 { major_name: 'Tecnología en sistematización de datos' },
                 { major_name: 'Tecnologías de información para el negocio' },
                 { major_name: 'Trabajo social' },
                 { major_name: 'Zootecnia' }
             ])

Language.create([
                    { language_name: 'Español' },
                    { language_name: 'Afrikáans' },
                    { language_name: 'Albanés' },
                    { language_name: 'Alemán' },
                    { language_name: 'Amhárico' },
                    { language_name: 'Árabe' },
                    { language_name: 'Armenio' },
                    { language_name: 'Azerí' },
                    { language_name: 'Bengalí' },
                    { language_name: 'Bielorruso' },
                    { language_name: 'Birmano' },
                    { language_name: 'Bosnio' },
                    { language_name: 'Búlgaro' },
                    { language_name: 'Camboyano' },
                    { language_name: 'Canarés' },
                    { language_name: 'Catalán' },
                    { language_name: 'Cebuano' },
                    { language_name: 'Checo' },
                    { language_name: 'Chichewa' },
                    { language_name: 'Chino' },
                    { language_name: 'Cingalés' },
                    { language_name: 'Coreano' },
                    { language_name: 'Corso' },
                    { language_name: 'Criollo haitiano' },
                    { language_name: 'Croata' },
                    { language_name: 'Danés' },
                    { language_name: 'Eslovaco' },
                    { language_name: 'Esloveno' },
                    { language_name: 'Esperanto' },
                    { language_name: 'Estonio' },
                    { language_name: 'Euskera' },
                    { language_name: 'Finlandés' },
                    { language_name: 'Francés' },
                    { language_name: 'Frisio' },
                    { language_name: 'Gaélico escocés' },
                    { language_name: 'Galés' },
                    { language_name: 'Gallego' },
                    { language_name: 'Georgiano' },
                    { language_name: 'Griego' },
                    { language_name: 'Gujarati' },
                    { language_name: 'Hausa' },
                    { language_name: 'Hawaiano' },
                    { language_name: 'Hebreo' },
                    { language_name: 'Hindi' },
                    { language_name: 'Hmong' },
                    { language_name: 'Holandés' },
                    { language_name: 'Húngaro' },
                    { language_name: 'Igbo' },
                    { language_name: 'Indonesio' },
                    { language_name: 'Inglés' },
                    { language_name: 'Irlandés' },
                    { language_name: 'Islandés' },
                    { language_name: 'Italiano' },
                    { language_name: 'Japonés' },
                    { language_name: 'Javanés' },
                    { language_name: 'Kazajo' },
                    { language_name: 'Kirguis' },
                    { language_name: 'Kurdo' },
                    { language_name: 'Lao' },
                    { language_name: 'Latín' },
                    { language_name: 'Letón' },
                    { language_name: 'Lituano' },
                    { language_name: 'Luxemburgués' },
                    { language_name: 'Macedonio' },
                    { language_name: 'Malayalam' },
                    { language_name: 'Malayo' },
                    { language_name: 'Malgache' },
                    { language_name: 'Maltés' },
                    { language_name: 'Maorí' },
                    { language_name: 'Maratí' },
                    { language_name: 'Mongol' },
                    { language_name: 'Nepalí' },
                    { language_name: 'Noruego' },
                    { language_name: 'Panyabí' },
                    { language_name: 'Pastún' },
                    { language_name: 'Persa' },
                    { language_name: 'Polaco' },
                    { language_name: 'Portugués' },
                    { language_name: 'Rumano' },
                    { language_name: 'Ruso' },
                    { language_name: 'Samoano' },
                    { language_name: 'Serbio' },
                    { language_name: 'Sesoto' },
                    { language_name: 'Shona' },
                    { language_name: 'Sindhi' },
                    { language_name: 'Somalí' },
                    { language_name: 'Suajili' },
                    { language_name: 'Sueco' },
                    { language_name: 'Sundanés' },
                    { language_name: 'Tagalo' },
                    { language_name: 'Tailandés' },
                    { language_name: 'Tamil' },
                    { language_name: 'Tayiko' },
                    { language_name: 'Telugu' },
                    { language_name: 'Turco' },
                    { language_name: 'Ucraniano' },
                    { language_name: 'Urdu' },
                    { language_name: 'Uzbeco' },
                    { language_name: 'Vietnamita' },
                    { language_name: 'Xhosa' },
                    { language_name: 'Yidis' },
                    { language_name: 'Yoruba' },
                    { language_name: 'Zulú' }
                ])

Tool.create([
                { tool_name: '3ds Max' },
                { tool_name: 'Adobe After Effects' },
                { tool_name: 'Adobe Dreamweaver' },
                { tool_name: 'Adobe Illustrator' },
                { tool_name: 'Adobe InDesign' },
                { tool_name: 'Adobe Photoshop' },
                { tool_name: 'Adobe Premiere Pro' },
                { tool_name: 'Altium' },
                { tool_name: 'ANSYS' },
                { tool_name: 'ArcGIS' },
                { tool_name: 'Arduino' },
                { tool_name: 'Arena' },
                { tool_name: 'Aspen Plus' },
                { tool_name: 'AutoCAD' },
                { tool_name: 'Bizagi BPM' },
                { tool_name: 'Bloomberg' },
                { tool_name: 'ChemDraw' },
                { tool_name: 'CorelDRAW' },
                { tool_name: 'Distribuciones Lynux' },
                { tool_name: 'Eclipse' },
                { tool_name: 'Excel - Macros' },
                { tool_name: 'Excel - Tablas dinámicas' },
                { tool_name: 'Final Cut' },
                { tool_name: 'GAMS' },
                { tool_name: 'Google Forms' },
                { tool_name: 'HELISA' },
                { tool_name: 'HFSS' },
                { tool_name: 'Inventor' },
                { tool_name: 'LaTex' },
                { tool_name: 'Lectra' },
                { tool_name: 'Lego Mindstorm NXT' },
                { tool_name: 'MATLAB' },
                { tool_name: 'Microsoft Access' },
                { tool_name: 'Microsoft Project' },
                { tool_name: 'Microsoft Visio' },
                { tool_name: 'Oracle Crystall Ball' },
                { tool_name: 'Regedit' },
                { tool_name: 'Rhino 3D' },
                { tool_name: 'Richpeace' },
                { tool_name: 'SAP' },
                { tool_name: 'SigmaPlot' },
                { tool_name: 'Siigo' },
                { tool_name: 'SketchUp' },
                { tool_name: 'Solid Edge' },
                { tool_name: 'SOLIDWORKS' },
                { tool_name: 'SPSS' },
                { tool_name: 'STATA' },
                { tool_name: 'Statgraphics' },
                { tool_name: 'Survey Monkey' },
                { tool_name: 'Windows Movie Maker' },
                { tool_name: 'WordPress' }
            ])

EducationLevel.create([
                          {level_name: 'Pregrado'},
                          {level_name: 'Licenciatura'},
                          {level_name: 'Especialización'},
                          {level_name: 'Maestría'},
                          {level_name: 'Doctorado'},
                          {level_name: 'Opción'},
                          {level_name: 'Énfasis'}
                      ])


# Linked with Company
Sector.create([
                  { sector_name: 'Agropecuario' },
                  { sector_name: 'Alimentos y Bebidas' },
                  { sector_name: 'Artes Graficas' },
                  { sector_name: 'Asociaciones y Cooperativas' },
                  { sector_name: 'Automotriz' },
                  { sector_name: 'Belleza y Estetica' },
                  { sector_name: 'Calzado' },
                  { sector_name: 'Comercio' },
                  { sector_name: 'Construccion' },
                  { sector_name: 'Cultural, Recreacion y Deporte' },
                  { sector_name: 'Editorial' },
                  { sector_name: 'Educacion' },
                  { sector_name: 'Eléctrico' },
                  { sector_name: 'Electronico' },
                  { sector_name: 'Farmaceutico' },
                  { sector_name: 'Financiero' },
                  { sector_name: 'Informatico y Software' },
                  { sector_name: 'Inmobiliario' },
                  { sector_name: 'Medio Ambiente' },
                  { sector_name: 'Metalúrgico' },
                  { sector_name: 'Minero y Petroleo' },
                  { sector_name: 'Muebles y Maderas' },
                  { sector_name: 'Papel y Cartón' },
                  { sector_name: 'Plásticos' },
                  { sector_name: 'Postal' },
                  { sector_name: 'Público' },
                  { sector_name: 'Químico' },
                  { sector_name: 'Salud' },
                  { sector_name: 'Seguridad Social' },
                  { sector_name: 'Servicios' },
                  { sector_name: 'Telecomunicaciones' },
                  { sector_name: 'Textil y Confección' },
                  { sector_name: 'Transportes y Almacenamiento' },
                  { sector_name: 'Turístico' }
              ])








































































































